apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: flask-hello:latest
          imagePullPolicy: IfNotPresent # Replace with your Docker image
          ports:
            - containerPort: 5000 # Replace with the port your application listens on
          # Replace with your environment variable
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: my-app
spec:
  type: LoadBalancer  # Change to NodePort if you're running locally
  ports:
    - port: 8080  # The port that will be exposed
      targetPort: 5000  # The port on which your app is running inside the container
      protocol: TCP
  selector:
    app: my-app

